### ISSUE TITLE
subscriber hanging after a while / fixed by passing restore_auth_on_reconnect=True to make_client

### ISSUE THREAD

**Issue by bsergean** [satori-com/satori-rtm-sdk-python#1]
We found out that the subscriber will hang after a while, possibly when the web-socket connection is dropped and `No hanlers could be found for logger "miniws4py"` is printed.

Adding `restore_auth_on_reconnect=True` to `make_client()` makes it work, so I wonder if this should become the default.

Thoughts ?
Thanks !

**Comment by bsergean** [comment]
I didn't find the problem, nor the solution, but I'm happy to be the messenger here to make the satori sdk better !

**Comment by satori-divanov** [comment]
Fixed in just released v1.0.3

**Comment by bsergean** [comment]
Thanks !

**Comment by bsergean** [comment]
Closing this as this appears to be fixed.
